# Whether this GitHub repo is for a CC-led engineering project
engineering_project: true
# Name of the repository/project in English
english_name: creativecommons.org - environment
# All technologies used
technologies: HTML, CSS, Javascript, PHP, Docker, Bash
# Whether this repository should be featured on the CC Open Source site's "Projects" page
featured: false
# Slack channel name (optional key)
slack: ''