# https://github.com/docker/compose/issues/4513#issuecomment-281478365
# >> Are we just expected to stay on [Docker Compose file format version 2] if
# >> we want to use docker-compose and not swarm mode?
# >
# > Yes.
#
# https://docs.docker.com/compose/compose-file/compose-file-v2/
version: '2.4'

services:

  ccsite-web:
    container_name: ccsite-web
    depends_on:
      - ccsite-wpdb
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        # Use dispatch port by default
        if ('${CODESPACE_NAME:-}') {
          define('WP_HOME', 'https://${CODESPACE_NAME:-}-8080.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-}');
          define('WP_SITEURL', 'https://${CODESPACE_NAME:-}-8080.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-}');
        } else {
          define('WP_HOME', 'http://localhost:8080');
          define('WP_SITEURL', 'http://localhost:8080');
        }
      WORDPRESS_DB_HOST: ccsite-wpdb:3306
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_name: wordpress
      WORDPRESS_USER: root
    # https://hub.docker.com/_/wordpress
    # https://github.com/docker-library/repo-info/blob/master/repos/wordpress/remote/latest.md
    # https://github.com/docker-library/repo-info/blob/master/repos/wordpress/local/latest.md
    image: wordpress:${WP_VERSION:?err}
    networks:
      - backend
    ports:
      - '8080:80'
    restart: on-failure
    volumes:
      # Apache2 web server configuration
      - ./config/web-sites-available:/etc/apache2/sites-available:ro
      # CC Legal Tools
      # - (assumes the cc-legal-tools-data repository has been cloned next to
      #   this repository)
      - ../cc-legal-tools-data:/var/www/git/cc-legal-tools-data:ro
      # Chooser
      # - (assumes the chooser repository has been cloned next to this
      #   repository) this repository)
      - ../chooser:/var/www/git/chooser:ro
      # FAQ
      # - (assumes the faq repository has been cloned next to this repository)
      #   this repository)
      - ../faq:/var/www/git/faq:ro
      # Platform Toolkit
      # - (assumes the mp repository has been cloned next to this repository)
      #   this repository)
      - ../mp:/var/www/git/mp:ro
      # WordPress
      - wp_data:/var/www/html
      # Migration cache
      - ./cache:/var/www/html/cache:ro

  ccsite-wpdb:
    container_name: ccsite-wpdb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    # https://hub.docker.com/_/mariadb
    image: mariadb
    networks:
      - backend
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql

  ccsite-phpmyadmin:
    container_name: ccsite-phpmyadmin
    depends_on:
      - ccsite-wpdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: ccsite-wpdb
      PMA_PORT: 3306
    # https://hub.docker.com/_/phpmyadmin
    image: phpmyadmin
    networks:
      - backend
    ports:
      - '8003:80'
    volumes:
      # Apache2 web server configuration
      - ./config/phpmyadmin-sites-available:/etc/apache2/sites-available:ro

  ccsite-composer:
    command: 'true'
    container_name: ccsite-composer
    depends_on:
      - ccsite-wpdb
      - ccsite-web
    # https://hub.docker.com/_/composer
    image: composer
    user: xfs
    volumes:
      - ./config/composer/composer.json:/var/www/html/composer.json
      - ./config/composer/composer.lock:/var/www/html/composer.lock
      - wp_data:/var/www/html
    working_dir: /var/www/html/

  ccsite-wpcli:
    container_name: ccsite-wpcli
    depends_on:
      - ccsite-wpdb
      - ccsite-web
    environment:
      WORDPRESS_DB_HOST: ccsite-wpdb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_USER: root
      WORDPRESS_USER: root
    # https://hub.docker.com/_/wordpress
    image: wordpress:cli
    networks:
      - backend
    user: xfs
    volumes:
      # WordPress
      - wp_data:/var/www/html
      # Migration cache
      - ./cache:/var/www/html/cache:ro

volumes:
  db_data:
  wp_data:

networks:
  backend:
