# https://docs.docker.com/compose/compose-file/compose-file-v2/

version: '2.4'

services:

  web:
    command: >
      bash -c '
        while !</dev/tcp/database/3306
        do
          echo -n "Waiting on database..."
          sleep 1
        done 2>/dev/null
        apache2-foreground'
    container_name: cc-web
    depends_on:
      - database
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        # Use dispatch port by default
        if ('${CODESPACE_NAME:-}') {
          define('WP_HOME', 'https://${CODESPACE_NAME:-}-8080.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-}');
          define('WP_SITEURL', 'https://${CODESPACE_NAME:-}-8080.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-}');
        } else {
          define('WP_HOME', 'http://localhost:8080');
          define('WP_SITEURL', 'http://localhost:8080');
        }
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_name: wordpress
      WORDPRESS_USER: root
    # https://hub.docker.com/_/wordpress
    # https://github.com/docker-library/repo-info/blob/master/repos/wordpress/remote/latest.md
    # https://github.com/docker-library/repo-info/blob/master/repos/wordpress/local/latest.md
    image: wordpress:${WP_VERSION:?err}
    networks:
      - backend
    ports:
      - '8080:80'
    restart: on-failure
    volumes:
      # Apache2 web server configuration
      - ./config/web-sites-available:/etc/apache2/sites-available:ro
      # CC Legal Tools
      # - (assumes the cc-legal-tools-data repository has been cloned next to
      #   this repository)
      - ../cc-legal-tools-data:/var/www/git/cc-legal-tools-data:ro
      # Chooser
      # - (assumes the chooser repository has been cloned next to this
      #   repository) this repository)
      - ../chooser:/var/www/git/chooser:ro
      # FAQ
      # - (assumes the faq repository has been cloned next to this repository)
      #   this repository)
      - ../faq:/var/www/git/faq:ro
      # Platform Toolkit
      # - (assumes the mp repository has been cloned next to this repository)
      #   this repository)
      - ../mp:/var/www/git/mp:ro
      # WordPress
      - wp_data:/var/www/html

  database:
    container_name: cc-wordpress-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    # https://hub.docker.com/_/mariadb
    image: mariadb
    networks:
      - backend
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: cc-phpmyadmin
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
      PMA_PORT: 3306
    # https://hub.docker.com/_/phpmyadmin
    image: phpmyadmin
    networks:
      - backend
    ports:
      - '8003:80'
    volumes:
      # Apache2 web server configuration
      - ./config/phpmyadmin-sites-available:/etc/apache2/sites-available:ro

  composer:
    command: 'true'
    container_name: cc-composer
    depends_on:
      - database
      - web
    # https://hub.docker.com/_/composer
    image: composer
    user: xfs
    volumes:
      - ./config/composer/composer.json:/var/www/html/composer.json
      - ./config/composer/composer.lock:/var/www/html/composer.lock
      - wp_data:/var/www/html
    working_dir: /var/www/html/

  wordpress-cli:
    container_name: cc-wpcli
    depends_on:
      - database
      - web
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_USER: root
      WORDPRESS_USER: root
    # https://hub.docker.com/_/wordpress
    image: wordpress:cli
    networks:
      - backend
    user: xfs
    volumes:
      - wp_data:/var/www/html

volumes:
  db_data:
  wp_data:

networks:
  backend:
